jobs:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.5.x-dev"
        - PHPUNIT_TEST=1
    - php: 7.2
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.6.x-dev"
        - PHPUNIT_TEST=1
        - COW_TEST=1
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.7.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_CWP_CWP_RECIPE_CMS="$REQUIRE_RECIPE 2.x-dev"
        - PHPUNIT_COVERAGE_TEST=1
