language: php

dist: xenial

# xvfb needs to be in this file, not in behat.yml as travis shared config does not currently seem to merge 'services'
services:
  - mysql
  - postgresql
  - xvfb

env:
  global:
    - SS_ENVIRONMENT_TYPE=dev
    - SS_BASE_URL="http://localhost:8080/"

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy
      - chromium-chromedriver
      - chromium-browser
