import:
  - config/before_script/main.yml
  - config/script/main.yml

language: php

dist: xenial

# xvfb needs to be in this file, not in behat.yml as travis shared config does not currently seem to merge 'services'
services:
  - mysql
  - postgresql
  - xvfb

env:
  global:
    - SS_ENVIRONMENT_TYPE=dev
    - REQUIRE_RECIPE_TESTING=^1

cache:
  directories:
    - $HOME/.composer/cache/files


after_failure:
  - if [[ $BEHAT_TEST ]]; php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/; fi
